"""Fixed the relations

Revision ID: 3a292b781ca4
Revises: 260949ab82cd
Create Date: 2023-09-23 11:39:51.097660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a292b781ca4'
down_revision = '260949ab82cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
