"""Fixed the relations for CAScade

Revision ID: ec3928d66209
Revises: 3a292b781ca4
Create Date: 2023-09-23 11:55:06.529508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec3928d66209'
down_revision = '3a292b781ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
